DROP TABLE IF EXISTS session_participants CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS participants CASCADE;
DROP TABLE IF EXISTS coaches CASCADE;

CREATE TABLE coaches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coach_id BIGINT NOT NULL,
    location VARCHAR(255) NOT NULL,
    zone_offset VARCHAR(100) NOT NULL,
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    end_time TIMESTAMP WITH TIME ZONE NOT NULL,
    capacity INTEGER NOT NULL CHECK (capacity > 0),
    CONSTRAINT fk_sessions_coaches FOREIGN KEY (coach_id) REFERENCES coaches (id) ON DELETE RESTRICT
);

CREATE TABLE session_participants (
    session_id BIGINT NOT NULL,
    participant_id BIGINT NOT NULL,
    registered_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_session_participants PRIMARY KEY (session_id, participant_id),
    CONSTRAINT fk_sp_sessions FOREIGN KEY (session_id) REFERENCES sessions (id) ON DELETE RESTRICT,
    CONSTRAINT fk_sp_participants FOREIGN KEY (participant_id) REFERENCES participants (id) ON DELETE RESTRICT
);

CREATE INDEX idx_sessions_coach_id ON sessions (coach_id);
CREATE INDEX idx_session_participants_participant_id ON session_participants (participant_id);
