ALTER TABLE coaches 
    ADD COLUMN first_name VARCHAR(255) NOT NULL DEFAULT 'TBD',
    ADD COLUMN last_name VARCHAR(255) NOT NULL DEFAULT 'TBD';

ALTER TABLE coaches 
    ALTER COLUMN first_name DROP DEFAULT,
    ALTER COLUMN last_name DROP DEFAULT;

ALTER TABLE coaches 
    ALTER COLUMN name DROP NOT NULL;
